### ISSUE TITLE
Allow to choose MIDI device

### ISSUE THREAD

**Issue by suhr** [monadgroup/axiom#152]
I tried to use MIDI (via [loopmidi](http://www.tobias-erichsen.de/software/loopmidi.html)) on Windows, but it didn't work. And when I tried to ensure that axiom uses the right midi device, I have found out there's no way to select a midi device.

**Comment by cpdt** [comment]
I'm assuming this is for the standalone editor? Yes, that doesn't support actual MIDI input at the moment (just 'previewing' with key presses). At the moment if you want to use MIDI input the best way is to run the Axiom VST plugin in a host that supports that.

I'll leave this open as a tracking issue for if/when MIDI input to the standalone editor is implemented, but it's not high on the list currently simply due to the fact that Axiom is primarily designed to work as a DAW plugin, we just have the standalone for testing/playing around with. But as always, if you or anyone else wants to take up the challenge, feel free to give implementing it yourself a shot! I'm always happy to provide a rough overview of what the changes would probably look like.

**Comment by nixpulvis** [comment]
How does one use the "MIDI Channel" module then?

**Comment by cpdt** [comment]
@nixpulvis "MIDI Channel" is a kind of filter for MIDI events. Each event has a channel number from 1-32, only those with a matching channel will "pass through" the MIDI Channel node. A lot of DAWs allow sending MIDI from different places to one plugin with a specific channel, so you could use the module here to 'emulate' multiple instruments in the one Axiom plugin instance.

**Comment by nixpulvis** [comment]
@cpdt Ah thanks, I get it. It would be really cool to have proper MIDI in/out support for the editor. I've got a few things I'd love to use together with this tool used as both a sequencer (MIDI out) and synth (MIDI in).
