### ISSUE TITLE
Can't reliably get the UI to show up after reloading Reaper project

### ISSUE THREAD

**Issue by Eugenio-Bruno** [monadgroup/axiom#172]
Hi,
I'm using the packed Axiom 0.4.3 win32 build with Reaper v5.80 x64.

When I create a new project I can open and close the Axiom UI without issue. I then save the project, close Reaper, and load the project again. There now seems to be no way to bring up the Axiom UI.

Let me know how I can help you improve this bug report, and thanks for this great project! :)

**Comment by cpdt** [comment]
Hey! Thanks for reporting the bug.

I did some investigation, and it looks like Reaper doesn't really like the way we currently show the editor window in the VST plugin, which is basically to just ignore the window it provides and open our own top-level one. Initially I did this since VST2 has a bunch of limitations around editor window interactions (e.g. with resizing), but since as you've discovered that doesn't work nicely with Reaper, I've now implemented proper embedding support so the editor will show in the window that the VST host provides (currently Windows only) which fixes the problem you reported.

The change is on master so the fix will be in 0.5.0, but I'm not sure how long it will be until that's released. Let me know if you need the fix in the meantime and I can get you a beta build, or you could try building it yourself.
