### ISSUE TITLE
A better value form system

### ISSUE THREAD

**Issue by cpdt** [monadgroup/axiom#8]
As part of [Controls Part II](https://github.com/monadgroup/axiom/wiki/Controls-Part-II) it would be nice to have a nicer value form system then what's currently implemented.

Basically, the current system tags each value with a form (eg linear, db, Q, note, freq, etc). A statement like `[lin] x` can then be used to convert the value in `x` to the linear form, internally using whatever form is stored in the value currently.

This makes sense in a localized environment, but when things start getting more complicated with interactive controls and connections, its harder to use and kinda error prone.

Part of the reason here is the ambiguity of values:

 - There is a `control` form that represents a value as how it would be displayed on a control (mapping to [0,1] and applying curves). But this means that putting a value into/reading one out of a control requires manual conversion to `control`.
 - There is an ambiguously named `linear` form, which is simply meant to be a number with no form - converting to/from it always returns the same number.
 - The above point also means that, for example, there's no way to convert a dB value into a linear (ie multiply-able value)

**Comment by PoroCYon** [comment]
So you basically need a type system that keeps track of dimension/unit of measurement, [like F# does](https://fsharpforfunandprofit.com/posts/units-of-measure/)?

`linear` then maps to a dimensionless value, and dB/MIDI note/frequency etc. would have their own unit.

Though, F#'s system has some problems, some practical, some in design:

* It doesn't know about "scaled dimensions", eg. that `100 cm == 1 m`, this needs an explicit conversion step in F#.
* It needs annotations and explicit conversions way too often
* The default type for function arguments/return types is dimensionless instead of generic. (This is a sane default for values, though.)
* *It has no distinction between linear, logarithmic, exponential, ... space, while this might be important.*

And, last but not least:

* Some way to bypass this will be needed, because of course. (see also: `reinterpret_cast`, `unsafePerformIO`, ...)

**Comment by cpdt** [comment]
Yep, that's basically what inspired it.  There's a version of it implemented in the language, but it has some issues that need to be worked out. The current syntax is like this:

```
# numeric literals are 'lin' by default
aNote = [note] 10
aFreq = [freq] aNote
# now aFreq is the frequency of aNote

# postfixes can be used
aDb = 10dB
aBigDb = 10kdb # the same as 10000db

# bypassing can be done like:
aDb = aFreq->[db]
```

Similar to what you've described, functions never 'convert' their input values based on it's form. Although their return values often aren't `lin`, typically based on their 'primary inputs' form.

So there are three main problems:
 - the set of forms and their conversions needs more thought to be useful. Also thinking about what should happen if you try and convert incompatible forms (forms are runtime not compile-time, so we can't just emit a compile error).
 - we need better (GUI based?) ways to reason about what forms values have across the graph - eg setting a controls 'main type' so any gets/sets to it convert to/from that type
 - how do controls handle this? Currently they just show whatever's put in directly, but I'm leaning towards converting internally based on the form to a control-friendly value

**Comment by PoroCYon** [comment]
> The set of forms and their conversions needs more thought to be useful

Here are some ideas (incomplete):

* Units: none, MIDI note, frequency (Hz or bpm), intensity (dB), time (s or beats), filter resonance (Q), ...
* Dimension/space: linear ('default'), logarithmic, exponential, snorm (for signals), and there should be some way to distinguish the number of channels. (Maybe vectorize all the things?)

I'm not sure on how many number types there should be: one (a float) is the easiest, but distinguishing between ints/floats (and their size) might be useful some day.

Another thing I'm not certain about is the distinction between the unit and what I'm calling the dimension or space, for the lack of a better word. If one value is linear, and another is logarithmic, adding them shouldn't be done "as usual", because it will result in badness. Though, some units only have one "dimension", so this could be baked-in, and either a special conversion or a type error should happen.

Conversions that need little or no context should be done implicitely (eg. MIDI note <-> frequency, and I guess Hz<->bpm and s<->beats as well, if the BPM is 'implicit' or global), I'm undecided about things like log + lin, type punning *must* be explicit (for obvious reasons), and trying to convert vastly different things should result in an error (eg. frequency -> audio signal, because an oscillator has to sit in the middle.)

> We need better (GUI based?) ways to reason about what forms values have across the graph

Perhaps the connections could be coloured, [as Max MSP does](http://mmmmaven.com/wp-content/uploads/SonicEchoes.jpg). Things like a level meter, scope view and FFT view could come in handy for debugging.

> setting a controls 'main type' so any gets/sets to it convert to/from that type

See above about the conversions, I guess? The 'main type' could then be inferred from the code.

> how do controls handle this? Currently they just show whatever's put in directly, but I'm leaning towards converting internally based on the form to a control-friendly value

See above `;)` (Unless I'm misunderstanding, of course. But conversion rules should be consistent between the node interface and Maxim code.)

> Also thinking about what should happen if you try and convert incompatible forms

Some sort of type error should emerge at "compile-time", imo, and the type information can be erased at runtime for performance and size. Of course, there isn't much difference between "compile-time" and "runtime" in the editor, and when compiling to the final thing, you could type-check once at "fake runtime", then erase that info.

How exactly the type checking and inferrence should happen is outlined in [this paper](http://typesatwork.imm.dtu.dk/material/TaW_Paper_TypesAtWork_Kennedy.pdf) (starting from §3), and some of the references are interesting as well.

---
Woah, that's a huge wall of text.

**Comment by PoroCYon** [comment]
> Those are roughly the same forms as what's currently implemented

I forgot two: frequency space (FFT out/IFFT in), and Z-space (Z-tf out/inv-Z-tf in, if there'd be a Z-transform).

> I like that idea, although of course there's the problem where different dimension spaces dont always make sense for all forms. Maybe extra forms would make sense? Eg [db] and then [amp] in linear form. I think this might be easier to understand than having form and dimension separate.

I was unsure about it as well, so I guess distinctions like dB and amp are good enough (and easier to implement).

> So all numbers are stereo floats. Based on talking with some other 64k musicians a while ago, I don't think there's much of a reason to have options for mono or stereo, ints, doubles, etc. It just overcomplicates things.

That's true, but I'm not sure that stereo is useful for *everything*, though. Some things might make more sense as mono-only (but I can't think of any examples now).

> there are some functions (eg sequence) which depend their output form on one of their parameters

The alternative would be type polymorphism... which would be a hell to implement.

> Also, compile-time forms introduce really high coupling between the code generation of two nodes, which pretty much makes it impossible to re-codegen one node in the editor while leaving the others.

The input and output types could be cached, and an error could be raised when they don't match with the new input/output types of the updated node.

> Ultimately runtime forms are almost always going to be optimized out by LLVM though, so I wouldn't be worried about their cost.

I guess this is fine when composing a song, and it's mostly ok for 64ks, but I'm not entirely sure about optimizations with smaller size classes.

> Basically though, the language is meant to be simple enough for a single-pass compiler to understand (because I don't have that much time to work on this), and for a musician (ie non computer scientist) to understand. Explicit conversions make what's happening really obvious and simplify the compiler a lot. You don't have to use them too much though, mostly just when calling into library functions.

Fair enough.

**Comment by cpdt** [comment]
> I forgot two: frequency space (FFT out/IFFT in), and Z-space (Z-tf out/inv-Z-tf in, if there'd be a Z-transform).

Yup. Although neither of these things (FFT or z-transforms) are currently on the near-future roadmap so I'm not too worried about this yet. Unless you want to give implementing them a shot :)

> That's true, but I'm not sure that stereo is useful for everything, though. Some things might make more sense as mono-only (but I can't think of any examples now).

For sure, but there's no real harm in handling everything as two channels. Math operators all work the same, and all numeric functions work with two channels - pretty much everything would end up as SSE instructions. Functions that don't care about both channels (eg some MIDI things) always just use the left one. Ultimately I think having the option to choose mono or stereo would just overcomplicate things a bit :)

> The input and output types could be cached, and an error could be raised when they don't match with the new input/output types of the updated node.

That could definitely work. I think I was more making a point towards inferring forms in that comment, that if inferring the form of a control required looking at another nodes codegen (which it would in >50%, of cases, as input forms can't be inferred from the local code), things would get messy fast. 

I think I'd like to avoid raising an error in nodes when other nodes change their external surface... especially since connections can span across multiple surfaces (with group nodes and exposed controls) I could imagine it'd be pretty frustrating. This is why I was thinking some kind of "main form", or "form guard" could be useful, pretty much ensuring a value read from a control had the right type no matter what's put into it by other nodes. But I'm open to trying this idea, if we can figure out how to report/handle it without interrupting the users flow.

I wouldn't worry too much about the optimization stuff at the moment... I've done pretty extensive testing and tuning to try and get the IR to match up well with what LLVM's optimizers expect, and at the moment it seems to do quite well reducing the code to exactly what's needed in the end. For example, an unoptimized conversion involves a call to a function with a switch, that dispatches calls based on the form of the input... since forms are almost always known at compile-time after some inlining, it's pretty much guaranteed that the required switch branch will be inlined somehow - unless you use one of the functions that doesn't have a static return form (eg `sequence`), then it'll include at least part of the switch and run exactly how you expect. Also, if LLVM doesn't optimize as expected, it's always possible to add our own optimization passes, although some kind of MIR would be useful for that (currently it's a single-pass conversion from AST to LLVM IR).

**Comment by PoroCYon** [comment]
> Although neither of these things (FFT or z-transforms) are currently on the near-future roadmap so I'm not too worried about this yet. Unless you want to give implementing them a shot :)

Yeah, I thought so.

I *could* try implementing it, but FFT things would need more thinking (filters make more sense for changing certain frequencies, and Paulstretch etc. wouldn't fit in a realtime context), and I have no idea how the Z-transform could be useful.

> For sure, but there's no real harm in handling everything as two channels... [snip]

Sounds fair. And LLVM would probably turn normal floating point math into SSE instructions as well, anyway. (Though, my Core2 can't handle all of them `:/`)

> I think I'd like to avoid raising an error in nodes when other nodes change their external surface... [snip]

The user has to be notified in some way (but preferably not in a very invasive way like suddenly showing a huge warning popup in the middle of a screen). Just blackholing errors isn't a very good idea either, imo, because it will make things less debuggable.

(Looks like I'm pushing for a stronger type system... for a synth...)

> I wouldn't worry too much about the optimization stuff at the moment... [snip]

Sounds OK, I guess. Over time, more agressive optimizations could be added (eg. detecting a linear system and converting the graph to a single, optimized matrix multiplication) or better (read: handcoded asm-emitting `;)`), but that shouldn't be needed for a first version.

**Comment by cpdt** [comment]
> FFT things would need more thinking (filters make more sense for changing certain frequencies, and Paulstretch etc. wouldn't fit in a realtime context)

Yep... I'm hoping to put FFT in at some point (just not near-future), Paulstretch is something that could come when samplers are implemented, although I haven't thought through how any of that's going to work yet.

> And LLVM would probably turn normal floating point math into SSE instructions as well, anyway. (Though, my Core2 can't handle all of them :/)

All numeric operations are emitted as vector operations, so yeah they'd typically be emitted as SSE instructions (although afaik that's configurable when running LLVM codegen). I wouldn't be surprised if vectors are also optimized into scalars when two channels aren't necessary, but I haven't actually done any testing to confirm that.

> The user has to be notified in some way (but preferably not in a very invasive way like suddenly showing a huge warning popup in the middle of a screen). Just blackholing errors isn't a very good idea either, imo, because it will make things less debuggable.

> (Looks like I'm pushing for a stronger type system... for a synth...)

Yeah, for sure. Something else that I completely forgot to mention before, the synth is built in a way so "coded" modules only exist at the lowest levels and users spend most of their time composing higher-level nodes that contain surfaces inside them. This probably wouldn't play well with compile-time forms, unless there's some concept of generic nodes, which I'd really rather avoid... I'm also concerned that having this stuff type-checked (or form-checked) is going to be a big flow disrupter for users, where things appear as though they should "just work" (if that makes sense). Of course, this does mean we end up with a weaker type system as you've mentioned, but ultimately I _think_ it's constrained enough that it's not too big of a deal (as long as we provide something to ensure a value is of the expected form from an input)... maybe larger projects will start to show holes in it though. Of course, I'd be open to making it stronger if we can figure out a way to make it still work ergonomically.

> Over time, more agressive optimizations could be added (eg. detecting a linear system and converting the graph to a single, optimized matrix multiplication) or better (read: handcoded asm-emitting ;)), but that shouldn't be needed for a first version.

With optimizations, I'd imagine we'd get much more benefit by tuning which LLVM passes we use rather than handcoding ASM. Most of the passes I've seen provide real benefits, and I'd rather not write a fully-fledged optimizer from scratch ;P. Of course, if handcoding ASM brings real benefits without complicating the codebase too much I'd be happy with that.

Matrix multiplication is a cool idea, I'd be interested to see how applicable it is to the kinds of synths people make.

Anyway, I think this discussion is starting to get a bit circular (unless you have anything else to add 🙂). In the short-term (ie not doing a massive change of the compiler and related concepts), right now I think less ambiguous form naming (and a more defined set of forms and their conversions), plus some kind of "form guard" on each control would do... although I'm not sure what this guard should look like. Thoughts?

**Comment by PoroCYon** [comment]
> Of course, this does mean we end up with a weaker type system as you've mentioned... [snip]

Yeah, I guess the exact balance will be hard to hit.

> With optimizations... [snip]

No comment ;)

> Anyway, I think this discussion is starting to get a bit circular

True that.

> although I'm not sure what this guard should look like. Thoughts?

Me neither. I'm thinking of a 'control' that has a single input and a single output (or n inputs and outputs) that filters out bad stuff, or errors on a bad type. Or perhaps embed the filter in a control input, or...

Problem is, none of them sound convincing to me.

**Comment by cpdt** [comment]
Well, I guess I should clarify how controls work currently. Basically, a control just represents a pointer to some memory. The memory is shared between "control groups", i.e. controls that are linked together share the same underlying memory. This means that controls don't have an intrinsic direction (ie input or output), although this can be roughly determined by looking at if the control value is written to or read from by the code.

The type of control acts as an interface between the code and the pointer, which means complex controls like ADSR curve editors, keyboards, or scopes can store additional information and provide a nice API. Basically when a property is read from or written to a control, a function for that control type is called.

I think the easiest way to "guard" values read from a control is to simply add a call to the converter function whenever a control is read. This means, say, reading a control with a guard form of `freq` would be equivalent to this code:

```
myFreq = [freq] in:num
```

(anything in the form `x:y` is a control, where `x` is the name and `y` is the control type - there can also optionally be a field specified with `x:y.z`)

This is simple enough to write once, but could become a bit annoying if you read the control's value more than once... typically you might say "just put it in a variable", but in a small 'scripty' language that's meant to be really short and quick to write that's kind of annoying to do. So ultimately, from the compiler/language perspective, adding some kind of builtin "guard" system wouldn't be necessary, but would be useful and probably make more sense from the POV of the user. It would be useful for the editor though, as it'd allow those controls to display their values better.

My original thought was to have a right click option on a control where a "main form" can be selected, although I'm not sure I like that since the state isn't immediately obvious, and it kinda feels like it should be declared somewhere in code. But declaring it alongside the control "variable" isn't great since it still requires it to be declared everywhere that control is used in the code.

**Comment by cpdt** [comment]
I recently implemented the enhancements mentioned above (except the "main form" picker), so I'll close this for now. At some point though I'd definitely like to look at a stricter system, maybe when I get around to making the compiler multi-pass (which is really needed atm).
